// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.qto.web.domain;

import com.qto.web.domain.Enrollment;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect Enrollment_Roo_Jpa_Entity {
    
    declare @type: Enrollment: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Enrollment.id;
    
    @Version
    @Column(name = "version")
    private Integer Enrollment.version;
    
    public Long Enrollment.getId() {
        return this.id;
    }
    
    public void Enrollment.setId(Long id) {
        this.id = id;
    }
    
    public Integer Enrollment.getVersion() {
        return this.version;
    }
    
    public void Enrollment.setVersion(Integer version) {
        this.version = version;
    }
    
}
