// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.qto.web.domain;

import com.qto.web.domain.Enrollment;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Enrollment_Roo_Configurable {
    
    declare @type: Enrollment: @Configurable;
    
}
