// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.qto.web.domain;

import com.qto.web.domain.Enrollment;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Enrollment_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager Enrollment.entityManager;
    
    public static final EntityManager Enrollment.entityManager() {
        EntityManager em = new Enrollment().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Enrollment.countEnrollments() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Enrollment o", Long.class).getSingleResult();
    }
    
    public static List<Enrollment> Enrollment.findAllEnrollments() {
        return entityManager().createQuery("SELECT o FROM Enrollment o", Enrollment.class).getResultList();
    }
    
    public static Enrollment Enrollment.findEnrollment(Long id) {
        if (id == null) return null;
        return entityManager().find(Enrollment.class, id);
    }
    
    public static List<Enrollment> Enrollment.findEnrollmentEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Enrollment o", Enrollment.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void Enrollment.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Enrollment.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Enrollment attached = Enrollment.findEnrollment(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Enrollment.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Enrollment.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Enrollment Enrollment.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Enrollment merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
