// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.qto.web.domain;

import com.qto.web.domain.Enrollment;
import com.qto.web.domain.Gamer;
import com.qto.web.domain.Tournament;
import java.util.Calendar;

privileged aspect Enrollment_Roo_JavaBean {
    
    public Gamer Enrollment.getGamer() {
        return this.gamer;
    }
    
    public void Enrollment.setGamer(Gamer gamer) {
        this.gamer = gamer;
    }
    
    public Tournament Enrollment.getTournament() {
        return this.tournament;
    }
    
    public void Enrollment.setTournament(Tournament tournament) {
        this.tournament = tournament;
    }
    
    public Calendar Enrollment.getRegistrationDate() {
        return this.registrationDate;
    }
    
    public void Enrollment.setRegistrationDate(Calendar registrationDate) {
        this.registrationDate = registrationDate;
    }
    
}
