// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.qto.web.controllers;

import com.qto.web.controllers.EnrollmentController;
import com.qto.web.domain.Enrollment;
import com.qto.web.domain.Gamer;
import com.qto.web.domain.Tournament;
import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.joda.time.format.DateTimeFormat;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect EnrollmentController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String EnrollmentController.create(@Valid Enrollment enrollment, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, enrollment);
            return "enrollments/create";
        }
        uiModel.asMap().clear();
        enrollment.persist();
        return "redirect:/enrollments/" + encodeUrlPathSegment(enrollment.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String EnrollmentController.createForm(Model uiModel) {
        populateEditForm(uiModel, new Enrollment());
        return "enrollments/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String EnrollmentController.show(@PathVariable("id") Long id, Model uiModel) {
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("enrollment", Enrollment.findEnrollment(id));
        uiModel.addAttribute("itemId", id);
        return "enrollments/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String EnrollmentController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("enrollments", Enrollment.findEnrollmentEntries(firstResult, sizeNo));
            float nrOfPages = (float) Enrollment.countEnrollments() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("enrollments", Enrollment.findAllEnrollments());
        }
        addDateTimeFormatPatterns(uiModel);
        return "enrollments/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String EnrollmentController.update(@Valid Enrollment enrollment, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, enrollment);
            return "enrollments/update";
        }
        uiModel.asMap().clear();
        enrollment.merge();
        return "redirect:/enrollments/" + encodeUrlPathSegment(enrollment.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String EnrollmentController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, Enrollment.findEnrollment(id));
        return "enrollments/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String EnrollmentController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Enrollment enrollment = Enrollment.findEnrollment(id);
        enrollment.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/enrollments";
    }
    
    void EnrollmentController.addDateTimeFormatPatterns(Model uiModel) {
        uiModel.addAttribute("enrollment_registrationdate_date_format", DateTimeFormat.patternForStyle("S-", LocaleContextHolder.getLocale()));
    }
    
    void EnrollmentController.populateEditForm(Model uiModel, Enrollment enrollment) {
        uiModel.addAttribute("enrollment", enrollment);
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("gamers", Gamer.findAllGamers());
        uiModel.addAttribute("tournaments", Tournament.findAllTournaments());
    }
    
    String EnrollmentController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
